Авторизація_робота адміна_Ready/MvcInternetApplication/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcInternetApplication.Models
{
    public class Film
    {
        public int FilmId { get; set; }

        [Required(ErrorMessage = "Вкажіть назву фільму")]
        public string FilmName { get; set; }

        [Required(ErrorMessage = "Вкажіть рейтинг")]
        public string FilmRating { get; set; }

        [Required(ErrorMessage = "Вкажіть країну походження")]
        public string FilmCountry { get; set; }

        [Required(ErrorMessage = "Вкажіть дату виходу")]
        public string FilmAge { get; set; }

        [Required(ErrorMessage = "Вкажіть тривалість фільму, хв")]
        public double FilmLength { get; set; }

        [Required(ErrorMessage = "Вкажіть жанр фільму")]
        public string FilmGenre { get; set; }

        [Required(ErrorMessage = "Вкажіть акторський склад")]
        public string FilmActors { get; set; }

        [StringLength(1000, MinimumLength = 7, ErrorMessage = "Потрібно вказати від 7 до 1000 символів")]
        public string FilmReview { get; set; }

        [Required(ErrorMessage = "Вкажіть місце знаходження зображеннь")]
        public string FilmPictures { get; set; }
        public int FilmPlus { get; set; }
        public int FilmMinus { get; set; }

        public List<Session> Session { get; set; }
    }
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Models/Review.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcInternetApplication.Models
{
    public class Review
    {
        public int FilmId_Review { get; set; }
        public string FilmName_Review { get; set; }

        public string FilmRating_Review { get; set; }
        public string FilmCountry_Review { get; set; }
        public string FilmAge_Review { get; set; }
        

        public double FilmLength_Review { get; set; }
        public string FilmGenre_Review { get; set; }

        public string FilmActors_Review { get; set; }
        public string FilmReview_Review { get; set; }
        public string FilmPictures_Review { get; set; }

        public int Plus_Review { get; set; }
        public int Minus_Review { get; set; }
    }
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcInternetApplication.Models;

namespace MvcInternetApplication.Controllers
{
    public class FilmsController : Controller
    {
        private AFISHAContext db = new AFISHAContext();

        //
        // GET: /Films/

        
        public ActionResult Index()
        {
            ViewBag.FilmName = new SelectList(db.Films, "FilmName", "FilmName");
            ViewBag.FilmGenre = new SelectList(new[] {"Фантастика", "Боевик","Триллер","Приключения"});
            ViewBag.FilmCountry = new SelectList(db.Films, "FilmCountry", "FilmCountry" );
            //ViewBag.FilmRating = new SelectList( db.Films, "FilmRating", "FilmRating");


            return View(db.Films);
        }
        //[HttpPost]
        //public ActionResult Index(string actor, string FilmGenre, string FilmName, string FilmCountry,string data)
        //{

        //    //ViewBag.IsAdmin= TempData["_UserName"] as string =="Admin"?"Admin":null;

        //    ViewBag.FilmName = new SelectList(db.Films, "FilmName", "FilmName");
        //    ViewBag.FilmGenre = new SelectList(new[] { "Фантастика", "Боевик", "Триллер", "Приключения" });
        //    ViewBag.FilmCountry = new SelectList(db.Films, "FilmCountry", "FilmCountry");
        //    //ViewBag.FilmRating = new SelectList(db.Films, "FilmRating", "FilmRating");


           
          
        //    var NAME = FilmName != "" ? db.Films.Where(x => x.FilmName.ToLower().Contains(FilmName.ToLower())) : db.Films;
        //    var GANRE = FilmGenre != "" ? db.Films.Where(x => x.FilmGenre.ToLower().Contains(FilmGenre.ToLower())) : db.Films;
        //    var ACTOR = actor != "" ? db.Films.Where(x => x.FilmActors.ToLower().Contains(actor.ToLower())) : db.Films;
        //    var COUNTRY = FilmCountry != "" ? db.Films.Where(x => x.FilmCountry.ToLower().Contains(FilmCountry.ToLower())) : db.Films;
        //    var DATA = data != "" ? db.Films.Where(x => x.FilmAge.ToLower().Contains(data.ToLower())) : db.Films;

        //    var All = NAME.Intersect(GANRE).Intersect(ACTOR).Intersect(COUNTRY).Intersect(DATA);

        //    return View(All);



        //}

        public ActionResult Sort()
        {    
            return PartialView(db.Films);
            
        }
        [HttpPost]
        public ActionResult Sort(string actor, string FilmGenre, string FilmName, string FilmCountry, string data)
        {

            //ViewBag.IsAdmin= TempData["_UserName"] as string =="Admin"?"Admin":null;

            ViewBag.FilmName = new SelectList(db.Films, "FilmName", "FilmName");
            ViewBag.FilmGenre = new SelectList(new[] { "Фантастика", "Боевик", "Триллер", "Приключения" });
            ViewBag.FilmCountry = new SelectList(db.Films, "FilmCountry", "FilmCountry");
            //ViewBag.FilmRating = new SelectList(db.Films, "FilmRating", "FilmRating");




            var NAME = FilmName != "" ? db.Films.Where(x => x.FilmName.ToLower().Contains(FilmName.ToLower())) : db.Films;
            var GANRE = FilmGenre != "" ? db.Films.Where(x => x.FilmGenre.ToLower().Contains(FilmGenre.ToLower())) : db.Films;
            var ACTOR = actor != "" ? db.Films.Where(x => x.FilmActors.ToLower().Contains(actor.ToLower())) : db.Films;
            var COUNTRY = FilmCountry != "" ? db.Films.Where(x => x.FilmCountry.ToLower().Contains(FilmCountry.ToLower())) : db.Films;
            var DATA = data != "" ? db.Films.Where(x => x.FilmAge.ToLower().Contains(data.ToLower())) : db.Films;

            var All = NAME.Intersect(GANRE).Intersect(ACTOR).Intersect(COUNTRY).Intersect(DATA);

            return PartialView(All);



        }

        //
        // GET: /Films/Details/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Details(int id = 0)
        {
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        //
        // GET: /Films/Create
        [Authorize(Roles = "Admin")]        
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Films/Create

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Film film)
        {
            if (ModelState.IsValid)
            {
                db.Films.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(film);
        }

        //
        // GET: /Films/Edit/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(int id = 0)
        {
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        //
        // POST: /Films/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Film film)
        {
            if (ModelState.IsValid)
            {
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(film);
        }

        //
        // GET: /Films/Delete/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Delete(int id = 0)
        {
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        //
        // POST: /Films/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = db.Films.Find(id);
            db.Films.Remove(film);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //вывод рецензии
        public ActionResult Review(string num)
        {
            
            if (num  !=null)
            {
                HttpContext.Response.Cookies["num_of_film"].Value = num;
                TempData["num_of_film"] = num;
            }
            else
            {
              num = HttpContext.Request.Cookies["num_of_film"].Value; 
            }

            int addressId = Int32.Parse(num);

            var review = db.Films.Where(s => s.FilmId == addressId).Select(n => new Review
            {

                FilmName_Review = n.FilmName,
                FilmGenre_Review = n.FilmGenre,
                FilmActors_Review = n.FilmActors,
                FilmId_Review = n.FilmId,
                FilmLength_Review=n.FilmLength,
                FilmReview_Review=n.FilmReview,
                FilmPictures_Review=n.FilmPictures,
                FilmAge_Review=n.FilmAge,
                FilmCountry_Review=n.FilmCountry,
                FilmRating_Review = n.FilmRating,
                Plus_Review = n.FilmPlus,
                Minus_Review = n.FilmMinus

            }).ToList()[0];
            
  
            return View(review);

            
            
        }
    [HttpPost]
        [Authorize]
        public ActionResult Review(int? numv,string action)
        {

            if (TempData.Peek("da") as string == null)
            {
                HttpContext.Response.Cookies["coment"].Value = "NO";
            }
            else
            {
                HttpContext.Response.Cookies["coment"].Value = "DA";
            }

            string res = HttpContext.Request.Cookies["coment"].Value;

            if (res == "DA")
            {
                return Content("<h1> Ви уже голосували </h1>");
            }
            else
            {
                int num = Convert.ToInt32(TempData.Peek("num_of_film") as string);
                Film reiting = db.Films.Find(num);
                switch (action)
                {
                    case "add": { reiting.FilmPlus++; } break;
                    case "minus": { reiting.FilmMinus++; } break;

                    default: ViewBag.Result = "ERRor"; break;
                }

                db.Entry(reiting).State = EntityState.Modified;
                db.SaveChanges();
                //COOKIES
                HttpContext.Response.Cookies["coment"].Value = "DA";
                TempData["da"] = "DA";

                int addressId = num;

                var review = db.Films.Where(s => s.FilmId == addressId).Select(n => new Review
                {

                    FilmName_Review = n.FilmName,
                    FilmGenre_Review = n.FilmGenre,
                    FilmActors_Review = n.FilmActors,
                    FilmId_Review = n.FilmId,
                    FilmLength_Review = n.FilmLength,
                    FilmReview_Review = n.FilmReview,
                    FilmPictures_Review = n.FilmPictures,
                    FilmAge_Review = n.FilmAge,
                    FilmCountry_Review = n.FilmCountry,
                    FilmRating_Review = n.FilmRating,
                    Plus_Review = n.FilmPlus,
                    Minus_Review = n.FilmMinus

                }).ToList()[0];
                            

                return View(review);

            }
        }

  

        public ActionResult LabelView(int num)
        {
            //creates partial label view

            var labels = db.UserComments.Where(s => s.ReviewID == num).Select(n => new Comment
            {
                FilmId = n.ReviewID,
                User_Name = n.Name,
                User_LabelText = n.LabelText,
                Date = n.Date,

            }).ToList();


            ViewBag.User_Comments_List_ForThisFilm = labels;


            return PartialView();

        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);

Авторизація_робота адміна_Ready/MvcInternetApplication/Controllers/UserCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcInternetApplication.Models;

namespace MvcInternetApplication.Controllers
{
    public class UserCommentsController : Controller
    {
        private AFISHAContext db = new AFISHAContext();

        //
        // GET: /UserComments/

        public ActionResult Index(string name,int? id)
        {
            var comment1 =name!=null ? db.UserComments.Where(x=>x.Name.Contains(name)).OrderByDescending(x=>x.Date):db.UserComments;
            var comment2 = id != null ? comment1.Where(x => x.ReviewID == id).OrderByDescending(x => x.Date) : db.UserComments;
            var comments = comment1.Intersect(comment2);
            return View(comments);
        }

        //
        // GET: /UserComments/Details/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Details(int id = 0)
        {
            UserComment usercomment = db.UserComments.Find(id);
            if (usercomment == null)
            {
                return HttpNotFound();
            }
            return View(usercomment);
        }

        //
        // GET: /UserComments/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserComments/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(UserComment usercomment)
        {
            usercomment.Date = DateTime.Now;
            TempData["UserMail"] = usercomment.E_mail;
            //usercomment.ReviewID = Convert.ToInt32(TempData["num_of_tank"] as string);
            usercomment.ReviewID = Convert.ToInt32(TempData.Peek("num_of_film") as string);


            //Якщо ім'я користувача буду вказане із "пробіл", то видалимо ці пробіли. БО НЕКОРЕКТНО ШУКАЄ ЗАПИСИ В ТАБЛИЦІ КОМЕНТАРІВ
            string[] split = usercomment.Name.Split(new Char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            usercomment.Name = split[0];
            if (ModelState.IsValid)
            {
                db.UserComments.Add(usercomment);
                db.SaveChanges();
                return RedirectToAction("Review", "Films", new { num = usercomment.ReviewID });


            }

            return View(usercomment);
        }

        //
        // GET: /UserComments/Edit/5
       [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(int id = 0)
        {
            UserComment usercomment = db.UserComments.Find(id);
            if (usercomment == null)
            {
                return HttpNotFound();
            }
            return View(usercomment);
        }

        //
        // POST: /UserComments/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(UserComment usercomment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usercomment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usercomment);
        }

        //
        // GET: /UserComments/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Delete(int id = 0)
        {
            UserComment usercomment = db.UserComments.Find(id);
            if (usercomment == null)
            {
                return HttpNotFound();
            }
            return View(usercomment);
        }

        //
        // POST: /UserComments/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult DeleteConfirmed(int id)
        {
            UserComment usercomment = db.UserComments.Find(id);
            db.UserComments.Remove(usercomment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/Films/Create.cshtml
@model MvcInternetApplication.Models.Film

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Film</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmName)
            @Html.ValidationMessageFor(model => model.FilmName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmRating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmRating)
            @Html.ValidationMessageFor(model => model.FilmRating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmCountry)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmCountry)
            @Html.ValidationMessageFor(model => model.FilmCountry)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.FilmAge)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmAge)
            @Html.ValidationMessageFor(model => model.FilmAge)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmLength)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmLength)
            @Html.ValidationMessageFor(model => model.FilmLength)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmGenre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmGenre)
            @Html.ValidationMessageFor(model => model.FilmGenre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmActors)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmActors)
            @Html.ValidationMessageFor(model => model.FilmActors)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmReview)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmReview)
            @Html.ValidationMessageFor(model => model.FilmReview)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmPictures)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmPictures)
            @Html.ValidationMessageFor(model => model.FilmPictures)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/Films/Delete.cshtml
@model MvcInternetApplication.Models.Film

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Film</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmLength)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmLength)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmGenre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmGenre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmActors)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmActors)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmPictures)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmPictures)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/Films/Details.cshtml
@model MvcInternetApplication.Models.Film

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Film</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmLength)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmLength)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmGenre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmGenre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmActors)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmActors)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilmPictures)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilmPictures)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.FilmId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/Films/Edit.cshtml
@model MvcInternetApplication.Models.Film

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Film</legend>

        @Html.HiddenFor(model => model.FilmId)

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmName)
            @Html.ValidationMessageFor(model => model.FilmName)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.FilmRating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmRating)
            @Html.ValidationMessageFor(model => model.FilmRating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmCountry)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmCountry)
            @Html.ValidationMessageFor(model => model.FilmCountry)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.FilmAge)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmAge)
            @Html.ValidationMessageFor(model => model.FilmAge)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmLength)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmLength)
            @Html.ValidationMessageFor(model => model.FilmLength)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmGenre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmGenre)
            @Html.ValidationMessageFor(model => model.FilmGenre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmActors)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmActors)
            @Html.ValidationMessageFor(model => model.FilmActors)
        </div>

          <div class="editor-label">
            @Html.LabelFor(model => model.FilmReview)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmReview)
            @Html.ValidationMessageFor(model => model.FilmReview)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilmPictures)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilmPictures)
            @Html.ValidationMessageFor(model => model.FilmPictures)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/Films/Index.cshtml
@model IEnumerable<MvcInternetApplication.Models.Film>

@{
    Layout = null;
    ViewBag.Title = "Index";
    AjaxOptions options = new AjaxOptions()
      {
          UpdateTargetId = "tabledata",
          Url = Url.Action("Sort", "Films"),
          HttpMethod = "POST",
          InsertionMode = InsertionMode.Replace

      };
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
    <script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.min.js" ></script>
   
</head>
<body>
  <div>
    @using (Ajax.BeginForm(options))
    {         
        <div>
            <label>Назва</label>
            @Html.DropDownList("FilmName", String.Empty)
            <br />
            <label>Країна</label>
            @Html.DropDownList("FilmCountry", String.Empty)

            <label>Дата Виходу</label>
            @Html.TextBox("data")
            <br />
            <label>Жанр</label>
            @Html.DropDownList("FilmGenre", String.Empty)
            <br />
            <label>Акторський склад</label>
            @Html.TextBox("actor")
            <br />

        </div>
        <p>
            <input type="submit" name="operation" value="Sort" />
        </p>
          
   
    }
    @if (TempData.Peek("_UserRole") as string == "Admin")
    {
        <p>
            @Html.ActionLink("Create new", "Create")
        </p> 
    }
     @* Аякс запрос вставлятиме дані в ось це місце*@
      <div id="tabledata">
          @Html.Action("Sort")
      </div>
   
      </div>
    @section scripts {
        <script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    }</body>
</html>

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/Films/LabelView.cshtml
@model MvcInternetApplication.Models.UserComment
@{
    List<MvcInternetApplication.Models.Comment> lables = ViewBag.User_Comments_List_ForThisFilm;
    var grid = new WebGrid(source: lables, rowsPerPage: 5);
    
}



<h1>Залиште ваш коментар:</h1>
@using (Html.BeginForm("Create", "UserComments"))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserComment</legend>

        <label>
            @Html.TextBoxFor(model => model.LabelText, new { @placeholder = "Повідомлення" })
            @Html.ValidationMessageFor(model => model.LabelText)
        </label>

        <label>
            @Html.TextBoxFor(model => model.E_mail, new { @placeholder = "E-mail" })
            @Html.ValidationMessageFor(model => model.E_mail)
        </label>

        <label>
            @Html.TextBoxFor(model => model.Name, new { @placeholder = "Ім'я" })
            @Html.ValidationMessageFor(model => model.Name)
        </label>

        @* <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>*@

        <p>
            <input type="submit" value="Create" id="but" />
        </p>
    </fieldset>
}


<h4>Відгуки:</h4>
<ul id="lists" class="feedback">
    @foreach (var v in lables)
    {
        <li>
            <div class="feedback-info">
                <div class="feedback-name">
                    @if (TempData.Peek("_UserRole") as string == "Admin" || TempData.Peek("_UserRole") as string == "Moderator")
                    {


                        string link1 = "/UserComments/Index?name=" + @v.User_Name;
                        string link2 = "&id=" + @v.FilmId;
                        string link = link1 + link2;
                        <a href=@link>@v.User_Name</a>
                    }
                    else
                    {
                        <p>@v.User_Name</p>
                    }



                </div>
                <div class="feedback-date">
                    <time datetime="2015-10-10">@v.Date</time>
                </div>
            </div>
            <div class="feedback-text">
                <p>@v.User_LabelText</p>
            </div>
        </li>
    }
    
     @*@grid.GetHtml(
   
    columns: grid.Columns(
    
    grid.Column(columnName: "User_Name"),
    grid.Column(columnName: "User_LabelText",header:"Повідомлення",canSort:false),
    grid.Column(columnName: "Date", header:"Дата")
      
    )
)*@
</ul>