Авторизація_робота адміна_Ready/MvcInternetApplication/Controllers/MovieHousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcInternetApplication.Models;

namespace MvcInternetApplication.Controllers
{
    public class MovieHousesController : Controller
    {
        private AFISHAContext db = new AFISHAContext();

        //
        // GET: /MovieHouses/

        public ActionResult Index(string name)
        {
            TempData["cinemainfo"] = name;
             
            var stations = name != null ? db.MovieHouses.Where(x => x.MovieHouseName.Contains(name)).OrderByDescending(x=>x.MovieHouseRating) : db.MovieHouses.OrderByDescending(x=>x.MovieHouseRating);

            
            return View(stations.ToList());
        }
        [HttpPost]
        public ActionResult Index(string action, string name1)
        {

            var NAME = TempData.Peek("cinemainfo") as string;
            MovieHouse reiting = db.MovieHouses.Find(1);
            switch (action)
            {
                case "add": { reiting.MovieHouseRating++; } break;
                case "minus": { reiting.MovieHouseRating--; } break;

                default: ViewBag.Result = "ERRor"; break;
            }
            
            db.Entry(reiting).State = EntityState.Modified;
            db.SaveChanges();

            MovieHouse reiting1 = db.MovieHouses.Find(1);
            
            var stations = NAME != null ? db.MovieHouses.Where(x => x.MovieHouseName.Contains(NAME)).OrderByDescending(x => x.MovieHouseRating) : db.MovieHouses.OrderByDescending(x => x.MovieHouseRating);


            return View(stations.ToList());
        }

        
        //
        // GET: /MovieHouses/Details/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Details(int id = 0)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            if (moviehouse == null)
            {
                return HttpNotFound();
            }
            return View(moviehouse);
        }

        //
        // GET: /MovieHouses/Create
        [Authorize(Roles = "Admin")] 
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MovieHouses/Create

        [HttpPost]
        [Authorize(Roles = "Admin")] 
        public ActionResult Create(MovieHouse moviehouse)
        {
            if (ModelState.IsValid)
            {
                db.MovieHouses.Add(moviehouse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(moviehouse);
        }

        //
        // GET: /MovieHouses/Edit/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(int id = 0)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            if (moviehouse == null)
            {
                return HttpNotFound();
            }
            return View(moviehouse);
        }

        //
        // POST: /MovieHouses/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(MovieHouse moviehouse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(moviehouse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(moviehouse);
        }

        //
        // GET: /MovieHouses/Delete/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Delete(int id = 0)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            if (moviehouse == null)
            {
                return HttpNotFound();
            }
            return View(moviehouse);
        }

        //
        // POST: /MovieHouses/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")] 
        public ActionResult DeleteConfirmed(int id)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            db.MovieHouses.Remove(moviehouse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public JsonResult GetData()
        {
            string cinemainfo=TempData.Peek("cinemainfo") as string;
           
            
            var stations = cinemainfo != null ? db.MovieHouses.Where(x => x.MovieHouseName.Contains(cinemainfo)).ToList() : db.MovieHouses.ToList();
            

            return Json(stations, JsonRequestBehavior.AllowGet);
        }
    }
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/MovieHouses/Create.cshtml
@model MvcInternetApplication.Models.MovieHouse

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>MovieHouse</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseName)
            @Html.ValidationMessageFor(model => model.MovieHouseName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseTelephone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseTelephone)
            @Html.ValidationMessageFor(model => model.MovieHouseTelephone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseAdress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseAdress)
            @Html.ValidationMessageFor(model => model.MovieHouseAdress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GeoLat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GeoLat)
            @Html.ValidationMessageFor(model => model.GeoLat)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GeoLong)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GeoLong)
            @Html.ValidationMessageFor(model => model.GeoLong)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/MovieHouses/Delete.cshtml
@model MvcInternetApplication.Models.MovieHouse

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MovieHouse</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MovieHouseName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MovieHouseName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MovieHouseTelephone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MovieHouseTelephone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MovieHouseAdress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MovieHouseAdress)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/MovieHouses/Details.cshtml
@model MvcInternetApplication.Models.MovieHouse

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MovieHouse</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MovieHouseName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MovieHouseName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MovieHouseTelephone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MovieHouseTelephone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MovieHouseAdress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MovieHouseAdress)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.MovieHouseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/MovieHouses/Edit.cshtml
@model MvcInternetApplication.Models.MovieHouse

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>MovieHouse</legend>

        @Html.HiddenFor(model => model.MovieHouseId)

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseName)
            @Html.ValidationMessageFor(model => model.MovieHouseName)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseRating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseRating)
            @Html.ValidationMessageFor(model => model.MovieHouseRating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseStars)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseStars)
            @Html.ValidationMessageFor(model => model.MovieHouseStars)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseTelephone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseTelephone)
            @Html.ValidationMessageFor(model => model.MovieHouseTelephone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MovieHouseAdress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MovieHouseAdress)
            @Html.ValidationMessageFor(model => model.MovieHouseAdress)
        </div>

           <div class="editor-label">
            @Html.LabelFor(model => model.GeoLong)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GeoLong)
            @Html.ValidationMessageFor(model => model.GeoLong)
        </div>
                
        <div class="editor-label">
            @Html.LabelFor(model => model.GeoLat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GeoLat)
            @Html.ValidationMessageFor(model => model.GeoLat)
        </div>

      

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/MovieHouses/GetData.cshtml
@{
    ViewBag.Title = "GetData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetData</h2>

Авторизація_робота адміна_Ready/MvcInternetApplication/Views/MovieHouses/Index.cshtml
@model IEnumerable<MvcInternetApplication.Models.MovieHouse>

@{
    ViewBag.Title = "Index";
     
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>

        </div>
    </section>
}

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <title>Google Maps API v3 - Getting Started</title>
    <link href="../css/default.css" rel="stylesheet" />
    <script type="text/javascript" src="../js/json2.js"></script>

    <!-- ---------- include api with params ------------- -->
    <script type="text/javascript"
        src="http://maps.google.com/maps/api/js?sensor=true">
                   @*Your key. Tham khảo tại: http://dev.vast.vn/tuananh/Web/C%C4%90077#chuong5*@
    </script>

    <script lang="ja">
        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        var map;
        var geocoder;

        function initialize() {
            geocoder = new google.maps.Geocoder();
            directionsDisplay = new google.maps.DirectionsRenderer();

            var Dnipropetrovsk = new google.maps.LatLng(48.460861, 35.056737);
            var mapOptions = {
                zoom: 12,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                center: Dnipropetrovsk
            };

            map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

            // Настраиваем красный маркер, который будет использоваться для центральной точки
            var myLatlng = new google.maps.LatLng(48.460861, 35.056737);

            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: 'ВИ тут'
            });
            // Берем для маркера иконку с сайта google
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/red-dot.png')



            // Получаем данные
            $.getJSON('@Url.Action("GetData", "MovieHouses")', function (data) {
                // Проходим по всем данным и устанавливаем для них маркеры



                $.each(data, function (i, item) {


                    var marker = new google.maps.Marker({
                        'position': new google.maps.LatLng(item.GeoLong, item.GeoLat),
                        'map': map,
                        'title': item.MovieHouseName


                    });


                    // Берем для этих маркеров синие иконки с сайта google
                    marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')



                    var contentString = "<div class='stationInfo'><h2>Кінотеатр " + item.MovieHouseName
                               + "</h2><div><h4>Рейтинг: " + item.MovieHouseRating
                               + "</h4></div>"
                    + "<div><img src=" + item.MovieHouseStars + " width='140' height='25'/>"

                    // Для каждого объекта добавляем доп. информацию, выводимую в отдельном окне
                    var infowindow = new google.maps.InfoWindow({
                        //content: "<div class='stationInfo'><h2>Станция " + item.PlaceName + "</h2><div><h4>Линия метро: "
                        //    + item.Line + "</h4></div><div><h4>Пассажиропоток: " + item.Traffic + " млн. человек</h4></div></div>"

                        content: contentString
                    });

                    // обработчик нажатия на маркер объекта
                    google.maps.event.addListener(marker, 'click', function () {
                        infowindow.open(map, marker);


                    });
                })
            });

            directionsDisplay.setMap(map);
            directionsDisplay.setPanel(document.getElementById("directionsPanel"));
        };

        function calcRoute() {
            var start = '';
            var end = '';




            start = document.getElementById('start').value;
            geocoder.geocode({ 'address': start }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    start = results[0].geometry.location;
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });

            end = document.getElementById('end').value;
            geocoder.geocode({ 'address': end }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    end = results[0].geometry.location;
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });


            var selectedMode = document.getElementById("mode").value;
            var request = {
                origin: start,
                destination: end,
                travelMode: google.maps.TravelMode[selectedMode]
            };
            directionsService.route(request, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                }
            });
        };

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</head>




<body>
    <div>
        @section scripts
        {
            <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
        }


        @if (TempData.Peek("_UserRole") as string == "Admin")
        {
            <p>
                @Html.ActionLink("Create New", "Create")
            </p>
        }

        <table id="tabledata">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MovieHouseName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MovieHouseTelephone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MovieHouseAdress)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.MovieHouseRating)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.GeoLat)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.GeoLong)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MovieHouseStars)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                string link = "MovieHouses/Index?name=" + @item.MovieHouseName.ToString();
                <tr>
                    <td>
                        <a href=@link>@Html.DisplayFor(modelItem => item.MovieHouseName)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MovieHouseTelephone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MovieHouseAdress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MovieHouseRating)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.GeoLong)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.GeoLat)
                    </td>

                    <td>
                        <img src="@item.MovieHouseStars" width='140' height='25'/>

                    </td>


                    <td>
                        @if (TempData.Peek("_UserRole") as string == "Admin")
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = item.MovieHouseId }) <br />
                            @Html.ActionLink("Details", "Details", new { id = item.MovieHouseId }) <br />
                            @Html.ActionLink("Delete", "Delete", new { id = item.MovieHouseId })<br />
                        }
                    </td>

                </tr>
            }


        </table>

    </div>
    <div>
        <label>Звідки:</label><input type="text" id="start" name="start" value="Академія митної служби України" />
        <label>Куди:</label><input type="text" id="end" name="end" value="Академія митної служби України" />
        <label>Оберіть транспорт:</label>
        <select id="mode">
            <option value="DRIVING">На авто</option>
            <option value="WALKING">Пішком</option>
            <option value="BICYCLING">На велосипеді не працює</option>
            <option value="TRANSIT">Громадський транспорт</option>
        </select>
        <button onclick="javascript: calcRoute();">Прокласти маршрут</button>
    </div>
    <div id="map_canvas" style="float: left; width: 650px; height: 700px;"></div>
    <div id="directionsPanel" style="float: left; width: 650px; height: 500px; overflow: auto;"></div>
</body>
</html>